### ISSUE TITLE
Error in KaiGenGothicCN theme (`parse_format!': wrong number of arguments (given 2, expected 0))

### ISSUE THREAD

**Issue by zyli5313** [chloerei/asciidoctor-pdf-cjk-kai_gen_gothic#10]
Hi,

I installed all asciidoctor-pdf-cjk-kai_gen_gothic and CN fonts are available at `/Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.1/data/fonts`. But I am getting the following error.

Could you tell me how can I fix it? Thanks!

`$ asciidoctor-pdf -r asciidoctor-pdf-cjk-kai_gen_gothic -a pdf-style=KaiGenGothicCN ../out/overview.adoc --trace

/Library/Ruby/Gems/2.3.0/gems/ttfunk-1.5.1/lib/ttfunk/table/post.rb:85:in `parse_format!': wrong number of arguments (given 2, expected 0) (ArgumentError)
	from /Library/Ruby/Gems/2.3.0/gems/ttfunk-1.5.1/lib/ttfunk/table/post.rb:81:in `parse!'
	from /Library/Ruby/Gems/2.3.0/gems/ttfunk-1.5.1/lib/ttfunk/table.rb:20:in `block in initialize'
	from /Library/Ruby/Gems/2.3.0/gems/ttfunk-1.5.1/lib/ttfunk/reader.rb:24:in `parse_from'
	from /Library/Ruby/Gems/2.3.0/gems/ttfunk-1.5.1/lib/ttfunk/table.rb:20:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/ttfunk-1.5.1/lib/ttfunk.rb:105:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/ttfunk-1.5.1/lib/ttfunk.rb:105:in `postscript'
	from /Library/Ruby/Gems/2.3.0/gems/ttfunk-1.5.1/lib/ttfunk/subset/base.rb:65:in `encode'
	from /Library/Ruby/Gems/2.3.0/gems/prawn-2.2.2/lib/prawn/font/ttf.rb:261:in `embed'
	from /Library/Ruby/Gems/2.3.0/gems/prawn-2.2.2/lib/prawn/font/ttf.rb:255:in `block in register'
	from /Library/Ruby/Gems/2.3.0/gems/pdf-core-0.7.0/lib/pdf/core/document_state.rb:62:in `block in before_render_actions'
	from /Library/Ruby/Gems/2.3.0/gems/pdf-core-0.7.0/lib/pdf/core/document_state.rb:62:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/pdf-core-0.7.0/lib/pdf/core/document_state.rb:62:in `before_render_actions'
	from /Library/Ruby/Gems/2.3.0/gems/pdf-core-0.7.0/lib/pdf/core/renderer.rb:188:in `render_header'
	from /Library/Ruby/Gems/2.3.0/gems/pdf-core-0.7.0/lib/pdf/core/renderer.rb:164:in `render'
	from /Library/Ruby/Gems/2.3.0/gems/prawn-2.2.2/lib/prawn/document.rb:378:in `render'
	from /Library/Ruby/Gems/2.3.0/gems/prawn-2.2.2/lib/prawn/document.rb:386:in `block in render_file'
	from /Library/Ruby/Gems/2.3.0/gems/prawn-2.2.2/lib/prawn/document.rb:386:in `open'
	from /Library/Ruby/Gems/2.3.0/gems/prawn-2.2.2/lib/prawn/document.rb:386:in `render_file'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:2828:in `write'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.6/lib/asciidoctor/document.rb:971:in `write'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.6/lib/asciidoctor.rb:1459:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.6/lib/asciidoctor.rb:1521:in `block in convert_file'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.6/lib/asciidoctor.rb:1521:in `open'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.6/lib/asciidoctor.rb:1521:in `convert_file'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.6/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.6/lib/asciidoctor/cli/invoker.rb:111:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.6/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.16/bin/asciidoctor-pdf:31:in `<top (required)>'
	from /usr/local/bin/asciidoctor-pdf:22:in `load'
	from /usr/local/bin/asciidoctor-pdf:22:in `<main>'`

**Comment by zyli5313** [comment]
Found the bug! It's due to corrupted fonts file. Re-download again will solve it.

Closing this.
