### ISSUE TITLE
error running asciidoctor-pdf-cjk-kai_gen_gothic-install

### ISSUE THREAD

**Issue by zhou0** [chloerei/asciidoctor-pdf-cjk-kai_gen_gothic#12]
[1/20] Downloading KaiGenGothicCN-Bold-Italic.ttf
Traceback (most recent call last):
	17: from /home/lzhou/bin/asciidoctor-pdf-cjk-kai_gen_gothic-install:23:in `<main>'
	16: from /home/lzhou/bin/asciidoctor-pdf-cjk-kai_gen_gothic-install:23:in `load'
	15: from /home/lzhou/.gem/ruby/gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.1/exe/asciidoctor-pdf-cjk-kai_gen_gothic-install:30:in `<top (required)>'
	14: from /home/lzhou/.gem/ruby/gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.1/exe/asciidoctor-pdf-cjk-kai_gen_gothic-install:30:in `chdir'
	13: from /home/lzhou/.gem/ruby/gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.1/exe/asciidoctor-pdf-cjk-kai_gen_gothic-install:31:in `block in <top (required)>'
	12: from /home/lzhou/.gem/ruby/gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.1/exe/asciidoctor-pdf-cjk-kai_gen_gothic-install:31:in `each_with_index'
	11: from /home/lzhou/.gem/ruby/gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.1/exe/asciidoctor-pdf-cjk-kai_gen_gothic-install:31:in `each'
	10: from /home/lzhou/.gem/ruby/gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.1/exe/asciidoctor-pdf-cjk-kai_gen_gothic-install:33:in `block (2 levels) in <top (required)>'
	 9: from /home/lzhou/.gem/ruby/gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.1/exe/asciidoctor-pdf-cjk-kai_gen_gothic-install:33:in `open'
	 8: from /home/lzhou/.gem/ruby/gems/asciidoctor-pdf-cjk-kai_gen_gothic-0.1.1/exe/asciidoctor-pdf-cjk-kai_gen_gothic-install:34:in `block (3 levels) in <top (required)>'
	 7: from /usr/share/ruby/open-uri.rb:35:in `open'
	 6: from /usr/share/ruby/open-uri.rb:735:in `open'
	 5: from /usr/share/ruby/open-uri.rb:165:in `open_uri'
	 4: from /usr/share/ruby/open-uri.rb:224:in `open_loop'
	 3: from /usr/share/ruby/open-uri.rb:224:in `catch'
	 2: from /usr/share/ruby/open-uri.rb:226:in `block in open_loop'
	 1: from /usr/share/ruby/open-uri.rb:755:in `buffer_open'
/usr/share/ruby/open-uri.rb:377:in `open_http': 403 Forbidden (OpenURI::HTTPError)

**Comment by xu4wang** [comment]
same here.

Checking the script:
https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/blob/master/exe/asciidoctor-pdf-cjk-kai_gen_gothic-install

It downloads fonts from
https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts/
and put them into FONT_DIR.

I tried to download manually, but above page returns 404.

**Comment by chloerei** [comment]
Sorry, This gem is no longer maintained, I suggest follow the asciidoctor-pdf theme guides to use your local font.

https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.0.beta.7/docs/theming-guide.adoc#custom-fonts

If you want to manually complete the install script, your can found fonts here: https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/tag/v0.1.0-fonts

**Comment by life888888** [comment]
https://github.com/life888888/asciidoctor-pdf-cjk-ext/releases/tag/v0.1.0

Fonts : 
- Noto Sans CJK
- Noto Sans Mono CJK
- Noto Serif CJK 
- 
Font Style:
- Regular
- Bold
- Bold Italic
- Italic

Support language:
- Simplified Chinese   sc  
- Traditional Chinese  tc 
- Hong Kong hk 
- Japanese jp
-  Korean kr

If you want Noto Serif CJK, and JP (Japanese) , download [notoserif-cjk-jp.zip](https://github.com/life888888/asciidoctor-pdf-cjk-ext/releases/download/v0.1.0/notoserif-cjk-jp.zip)

If you want Noto Sans Mono CJK, and TC (Traditional Chinese)  , download [notosansmono-cjk-tc.zip](https://github.com/life888888/asciidoctor-pdf-cjk-ext/releases/download/v0.1.0/notosansmono-cjk-tc.zip)

If you want Noto Sans CJK, and SC (Simplified Chinese) , download [notosans-cjk-sc.zip](https://github.com/life888888/asciidoctor-pdf-cjk-ext/releases/download/v0.1.0/notosans-cjk-sc.zip)

Support Theme list is here:  https://github.com/life888888/asciidoctor-pdf-cjk-ext/blob/main/ThemeList.adoc

Every zip include 6 theme (For Asciidoctor PDF 2.x Theme , For Asciidoctor PDF 1.x Theme)

**Naming Rule is:**
- default-ext-notosans-cjk-xx
- default-notosans-cjk-xx
- notosans-cjk-xx-theme


**For Asciidoctor PDF 2.x Theme:**
- default-ext-notoFONTXXX-cjk-xx
- default-notoFONTXXX-cjk-xx
- notoFONTXXX-cjk-xx

**For Asciidoctor PDF 1.x Theme**
- default-ext-notoFONTXXX-cjk-xx-pdf-1
- default-notoFONTXXX-cjk-xx-pdf-1
- notoFONTXXX-cjk-xx-pdf-1

Font List
![asciidoctor-pdf-cjk-ext-fonts-1](https://user-images.githubusercontent.com/101442875/198204652-4cdb24bf-5369-4abb-a486-48c4e8581421.png)

Theme List
![asciidoctor-pdf-cjk-ext-themes-1](https://user-images.githubusercontent.com/101442875/198204674-fee0f269-c4e2-49e2-aebd-a2374ddb1903.png)

**Comment by life888888** [comment]
https://github.com/life888888/asciidoctor-pdf-cjk-ext/blob/main/install-zip-to-downloaded-resources-dir.sh

provide download shell script but only for linux, bash.

execute `./install-zip-to-downloaded-resources-dir.sh sc`

will auto download SC (Simplified Chinese) - ( sans, snasmono, serif )

**Comment by life888888** [comment]
Download Noto CJK Fonts TTF

https://github.com/life888888/cjk-fonts-ttf#download-fonts
