### ISSUE TITLE
undefined method `unpack' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by ioiioi** [chloerei/asciidoctor-pdf-cjk-kai_gen_gothic#6]
hello @chloerei 

我在使用asciidoctor-pdf-cjk-kai_gen_gothic生成pdf的时候出现了一个错误，详情如下：

```
$ asciidoctor-pdf -r asciidoctor-pdf-cjk-kai_gen_gothic -a pdf-style=KaiGenGothicCN 2015-01-01-first-entry.adoc --trace
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/directory.rb:11:in `block in initialize': undefined method `unpack' for nil:NilClass (NoMethodError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/directory.rb:10:in `times'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/directory.rb:10:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk.rb:41:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk.rb:41:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk.rb:13:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk.rb:13:in `open'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font/ttf.rb:354:in `read_ttf_file'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font/ttf.rb:26:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:287:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:287:in `load'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:243:in `find_font'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:57:in `font'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/prawn_ext/extensions.rb:225:in `font'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:2402:in `theme_font'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:1054:in `block in convert_listing_or_literal'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/prawn_ext/extensions.rb:791:in `instance_exec'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/prawn_ext/extensions.rb:791:in `block in dry_run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:62:in `block in font'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:207:in `save_font'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/prawn-2.1.0/lib/prawn/font.rb:60:in `font'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/prawn_ext/extensions.rb:225:in `font'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/prawn_ext/extensions.rb:790:in `dry_run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/prawn_ext/extensions.rb:806:in `keep_together'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:1052:in `convert_listing_or_literal'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:103:in `convert'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/abstract_block.rb:71:in `convert'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/abstract_block.rb:80:in `block in content'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/abstract_block.rb:80:in `map'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/abstract_block.rb:80:in `content'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:119:in `convert_content_for_block'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:358:in `convert_section'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:103:in `convert'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/abstract_block.rb:71:in `convert'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/abstract_block.rb:80:in `block in content'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/abstract_block.rb:80:in `map'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/abstract_block.rb:80:in `content'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:1110:in `content'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:119:in `convert_content_for_block'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:177:in `convert_document'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/lib/asciidoctor-pdf/converter.rb:103:in `convert'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:1050:in `convert'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor.rb:1506:in `convert'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:95:in `block in invoke!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:87:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:87:in `invoke!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-pdf-1.5.0.alpha.13/bin/asciidoctor-pdf:31:in `<top (required)>'
        from C:/Ruby23-x64/bin/asciidoctor-pdf:23:in `load'
        from C:/Ruby23-x64/bin/asciidoctor-pdf:23:in `<main>'
```

不知道是什么原因？

**Comment by ioiioi** [comment]
经过测试，假如在asciidoc文档里面包含了source的话，就出现这个故障，譬如：

```
[source]
----
$ sudo ls
----
```

然而，如果我直接用：

```
$ asciidoctor-pdf 2015-01-01-first-entry.adoc
```

即便包含了source，也是没问题的，只是中文有缺字，多出很多空白。

**Comment by chloerei** [comment]
推荐先转成 html，然后用 http://wkhtmltopdf.org/ 转成 PDF。

**Comment by yurenji** [comment]
> undefined method `/' for nil:NilClass (NoMethodError)

类似的问题， 有什么建议吗？  尝试convert的[文件](https://github.com/inoutcode/ethereum_book/blob/master/%E7%AC%AC%E4%B8%80%E7%AB%A0.asciidoc)： 

```
$ asciidoctor-pdf -r asciidoctor-pdf-cjk-kai_gen_gothic -a pdf-style=KaiGenGothicCN 第一章.asciidoc --trace
/Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.4/lib/asciidoctor-pdf/converter.rb:717:in `convert_admonition': undefined method `/' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.4/lib/asciidoctor-pdf/converter.rb:135:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.4/lib/asciidoctor-pdf/converter.rb:151:in `convert_content_for_block'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.4/lib/asciidoctor-pdf/converter.rb:552:in `convert_section'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.4/lib/asciidoctor-pdf/converter.rb:135:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.4/lib/asciidoctor-pdf/converter.rb:151:in `convert_content_for_block'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.4/lib/asciidoctor-pdf/converter.rb:552:in `convert_section'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.4/lib/asciidoctor-pdf/converter.rb:135:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:1020:in `content'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.4/lib/asciidoctor-pdf/converter.rb:151:in `convert_content_for_block'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.4/lib/asciidoctor-pdf/converter.rb:262:in `convert_document'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.4/lib/asciidoctor-pdf/converter.rb:135:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:118:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
	from /Library/Ruby/Gems/2.3.0/gems/asciidoctor-pdf-1.5.0.beta.4/bin/asciidoctor-pdf:32:in `<top (required)>'
	from /usr/local/bin/asciidoctor-pdf:22:in `load'
	from /usr/local/bin/asciidoctor-pdf:22:in `<main>'
```
